### ISSUE TITLE
Add new server:status command

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#21]
This command should print something like this on stdout:

```
Deployment: Available
Pod:
  - Name: che-wxzyld
  - Phase: Running
Ingress: 
Workspaces:
  - chectl: Running
  - wks-dfker: Stopped
Persistent Volume Path: /path/to/local/storage
Version: 6.16.0-SNAPSHOT
```
